# Generated by Django 3.0.3 on 2020-03-30 23:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeAutor', models.CharField(max_length=45, verbose_name='DescNomeCliente')),
                ('dtCadastro', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Data de cadastro')),
                ('dtEdicao', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Data da última edição')),
                ('usuarioCadastro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='UsuarioCadastroAutor', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
                ('usuarioEdicao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='UsuarioEdicaoAutor', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'db_table': 'Autor',
            },
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descGenero', models.CharField(max_length=45, verbose_name='DescNomeCliente')),
                ('dtCadastro', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Data de cadastro')),
                ('dtedicao', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Data da última edição')),
                ('usuarioCadastro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='UsuarioCadastro', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
                ('usuarioEdicao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='UsuarioEdicao', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'db_table': 'Genero',
            },
        ),
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeLivro', models.CharField(max_length=45, verbose_name='DescNomeCliente')),
                ('dtCadastro', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Data de cadastro')),
                ('dtEdicao', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Data da última edição')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Autor', to='Gestao.Autor', verbose_name='Autor')),
                ('genero', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Genero', to='Gestao.Genero', verbose_name='Genero')),
                ('usuarioCadastro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='UsuarioCadastroLivro', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
                ('usuarioEdicao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='UsuarioEdicaoLivro', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'db_table': 'Livro',
            },
        ),
        migrations.CreateModel(
            name='Locacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dtCadastro', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Data de cadastro')),
                ('livro', models.ManyToManyField(to='Gestao.Livro')),
                ('usuarioCadastro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='UsuarioCadastroLocacao', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'db_table': 'Locacao',
            },
        ),
    ]
