# Generated by Django 3.0.3 on 2020-03-30 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Gestao', '0002_auto_20200330_2346'),
    ]

    operations = [
        migrations.RenameField(
            model_name='genero',
            old_name='dtdicao',
            new_name='dtEdicao',
        ),
    ]
